services:
  translator-api:
    build: .
    container_name: translator-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - TRANSLATION_API_KEY=de7a2c67a7a7621d6b02e0c8d2f21413d4dff3eb10087d219c1b3efacdb31246
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: translator-redis
    restart: unless-stopped
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    networks:
      - backend

volumes:
  redis-data:

networks:
  backend:
    driver: bridge
